feat: update usage of chain-co / 升级 chain-co 的相关使用
filecoin-project/venus-docs pull request #361
Opened 2022-12-19 05:52 UTC by LinZexiao

## 关联的Issues (Related Issues)

close

## 改动 (Proposed Changes)

## 附注 (Additional Info)

## 自查清单 (Checklist)

在你认为本 PR 满足被审阅的标准之前，需要确保 / Before you mark the PR ready for review, please make sure that:
- [ ] 符合Venus项目管理规范中关于PR的[相关标准](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/PR%E5%91%BD%E5%90%8D%E8%A7%84%E8%8C%83.md) / The PR follows the PR standards set out in the Venus project management guidelines
- [ ] 符合[venus-docs文档规范](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)
- [ ] 具有清晰明确的[commit message](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/git%E4%BD%BF%E7%94%A8/commit-message%E9%A3%8E%E6%A0%BC%E8%A7%84%E8%8C%83.md) / All commits have a clear commit message.

2022-12-19 09:19 UTC, simlecode commented on docs/zh/operation/README.md
> -./chain-co  run -listen 0.0.0.0:<port> --auth-url <venus-auth url> --node <token:libp2p> --node<token:libp2p>
上面checkout 的版本换成v0.2.0的吧

2022-12-19 09:19 UTC, simlecode commented on docs/operation/README.md
> +./chain-co --listen 0.0.0.0:<port>  run --auth-url <venus-auth url> --node <token:rpc-url> --node<token:rpc-url>
上面checkout 的版本换成v0.2.0的吧

2022-12-19 09:23 UTC, Fatman13 requested changes

2022-12-19 09:23 UTC, Fatman13 commented on docs/zh/operation/README.md
> +节点授权这里建议连接venus-auth进行授权，不然节点重启时,token会发生变化。
```suggestion
节点授权这里建议连接`venus-auth`进行授权，不然节点重启时，`token`会发生变化。
```
改个标点。

2022-12-21 02:43 UTC, simlecode approved these changes
LGTM

2022-12-21 08:05 UTC, Fatman13 approved these changes
LGTM

2022-12-21 08:05 UTC, merged